### ISSUE TITLE
Installation problem with "laravel/framework": "^8.0" in vagrant box

### ISSUE THREAD

**Issue by javiya-rupal** [composer/package-versions-deprecated#14]
- Installing composer/package-versions-deprecated (1.11.99): Loading from cache
Plugin installation failed (include(/home/vagrant/my-app/vendor/composer/package-versions-deprecated/src/PackageVersions/Installer.php): failed to open stream: No such file or directory), rolling back
  - Removing composer/package-versions-deprecated (1.11.99)

Installation failed, reverting ./composer.json to its original content.
                                                                                                                  
  [RuntimeException]                                                                                              
  Could not delete /home/vagrant/my-app/vendor/composer/package-versions-deprecated/src/PackageVersions:

**Comment by Seldaek** [comment]
Do other installs work? Can you install a package in that vagrant box and check if the vendor dir contains the files as expected?

**Comment by javiya-rupal** [comment]
Yes other installation works.
I was trying to install package in vagrant only and yes vendor directory contains expected file of package.the only issue is with permission.
Whenever I try to install package, it create new files everytime inside composer/packages-versions-deprecated/src/PackageVersions

**Comment by Seldaek** [comment]
Sorry but I don't see what's so special about that package that it would cause issues. Are you using Composer 2 or 1? Can you post the full output of the composer command you are running?

**Comment by javiya-rupal** [comment]
**Composer version 1.10** I am using. and here is the screenshot for error when I run package installation.

<img width="1210" alt="Screenshot 2020-10-27 at 10 38 21" src="https://user-images.githubusercontent.com/25384154/97284601-86e49400-1841-11eb-9f97-e1670dcd6dc4.png">

**Comment by Seldaek** [comment]
Ok, no idea what is causing this. I'd try to do this outside of vagrant to see if it's caused by the vagrant filesystem perhaps.

Or you can also try to run `composer clearcache` just in case the cached archive for that package is corrupt somehow.

**Comment by Seldaek** [comment]
And you could try to `composer self-update --2` to get composer 2, see if it helps.. But you will have to remove hirak/prestissimo then.

**Comment by javiya-rupal** [comment]
Yes. issue because of vagrant only. I will try if I can install it outside of vagrant anyway.
Thanks for the help @Seldaek

**Comment by Seldaek** [comment]
Or maybe try to update vagrant / virtualbox to latest, might be a bug in there that got fixed already

**Comment by panvid** [comment]
I have the same problem, not with laravel, but doctrine. It also uses *composer/package-versions-deprecated*.

- latest Composer *2.0.4*
- latest Vagrant (2.2.7)
- latest virtualbox (6.1.14)


Clearing Composer-Cache does not fix it. Removing *vendor* folder also does not fix it.

```
vagrant@dp_vagrant_box:/var/www/html$ composer update
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 142 installs, 0 updates, 0 removals
  - Installing composer/package-versions-deprecated (1.11.99): Extracting archive
    Install of composer/package-versions-deprecated failed

                                                                                                                 
  [RuntimeException]                                                                                             
  Could not delete /var/www/html/vendor/composer/package-versions-deprecated/src/PackageVersions/Installer.php:  
                                                                                                                 

update [--with WITH] [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```

**Comment by Seldaek** [comment]
@dpauli as per the discussion above, seems to be a bug in the virtualbox filesystem, not something we can fix I'm afraid. Please report it to them.

**Comment by metalagman** [comment]
Found temporal solution in adding ```"ocramius/package-versions": "2.1.0"``` to the `require` section of composer.json.
