### ISSUE TITLE
Installing via Composer fails

### ISSUE THREAD

**Issue by chriskonnertz** [composer/package-versions-deprecated#24]
Hello,

I am trying to install https://github.com/barryvdh/laravel-ide-helper via Composer.
Apparently `composer/package-versions-deprecated` is a dependency of the library, and Composer fails to install it:

>  Installing composer/package-versions-deprecated (1.11.99.1): Extracting archive
> Plugin initialization failed (include(/home/vagrant/code/****/vendor/composer/package-versions-deprecated/src/PackageVersions/Installer.php): Failed to open stream: No such file or directory), uninstalling plugin
>  - Removing composer/package-versions-deprecated (1.11.99.1)
>    Install of composer/package-versions-deprecated failed
>
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

OS: Linux (Ubuntu 20.04) via Laravel Homestead in Vagrant
PHP: 8.0.1
Composer: 2.0.11

Any idea why this is happening?

**Comment by hacfi** [comment]
Hi @chriskonnertz,
had the same issue the last several hours. Now after waiting a bit and restarting I was able to install it. It could potentially be a GitHub rate limit issue. Were you installing a lot of other packages at the same time/a bit earlier?

**Comment by chriskonnertz** [comment]
Hi @hacfi ,
I don't think it's that. I have tried it many times on different days but without any success.

**Comment by chriskonnertz** [comment]
Solved. I tried out different things. Finally I tried to update Composer and wow, after updating from 2.0.11 to 2.0.12 it worked. :+1:
