### ISSUE TITLE
Update README.md with information how to use this package

### ISSUE THREAD

**Issue by kubawerlos** [composer/package-versions-deprecated#31]
Should it be [required directly as `vimeo/psalm` does](https://github.com/vimeo/psalm/blob/4.10.0/composer.json#L27) or with `"composer-runtime-api": "^2.0",` in `composer.json` as `infection/infection` does?

**Comment by Seldaek** [comment]
If you require composer-runtime-api, you should use the native Composer 2 class `Composer\InstalledVersions` documented here https://getcomposer.org/doc/07-runtime.md#installed-versions

This package here should not be used anymore, it's just here as a way to allow smooth migration from ocramius/package-versions to the native Composer API. The long term goal is that it would not be used anymore.
