### ISSUE TITLE
PHP 8 is not allowed by the PHP version constraint

### ISSUE THREAD

**Issue by morozov** [composer/package-versions-deprecated#7]
The package description states that it:

> […] provides compatibility with Composer 1 and 2 on PHP 7+

It implies that PHP 8 is also supported but it's not allowed by the PHP version constraint:

https://github.com/composer/package-versions-deprecated/blob/dd51b4443d58b34b6d9344cf4c288e621c9a826f/composer.json#L16-L17

**Comment by morozov** [comment]
@Seldaek is it a valid issue or I'm doing something wrong? See https://github.com/doctrine/dbal/issues/4200#issuecomment-670726800.

**Comment by Seldaek** [comment]
Yup seems valid just haven't had time to deal with it yet.

**Comment by Seldaek** [comment]
1.10.99.1 is out fixing this.

**Comment by morozov** [comment]
Thanks, @Seldaek!
