### ISSUE TITLE
The implementation based on Composer 2 InstalledVersions is broken for the root package

### ISSUE THREAD

**Issue by stof** [composer/package-versions-deprecated#8]
The `ocramius/package-versions` API supports passing the name of the root package to `getVersion` (and exposes a constant holding it). The `Composer/InstalledVersions` API does not support the root package in `getVersion` (only dependencies are there), but has a separate API to access the info about the root package. But the fallback implementation does not account for it.

**Comment by Seldaek** [comment]
Yeah 1.10.2 and 1.11.0 need to be backported here it seems.. @nicolas-grekas if you feel like helping out with this again :)

**Comment by Jean85** [comment]
2.0 from upstream should totally fix this, but requires Composer 2 :sweat_smile:  https://github.com/Ocramius/PackageVersions/pull/155
It should be backported too, it should be the final step of the upgrade path.

**Comment by Seldaek** [comment]
I guess yeah. The waste of time goes on..

**Comment by Seldaek** [comment]
About 2.0 I am not 100% sure if it matters, at that point you might as well be using the Composer 2 API directly as 2.0 requires composer 2 anyway..
